# Generated by Django 2.0.4 on 2018-04-14 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名')),
                ('status', models.CharField(choices=[(1, 'LIVE'), (0, 'DEAD')], default=1, max_length=10, verbose_name='仓库状态')),
                ('freq', models.IntegerField(default=0, verbose_name='使用频率')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_active_time', models.DateTimeField(auto_now=True, verbose_name='最近操作时间')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('code', models.TextField(verbose_name='标识码')),
                ('remarks', models.TextField(verbose_name='备注信息')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_active_time', models.DateTimeField(auto_now=True, verbose_name='最近操作时间')),
                ('belong', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mycode.Directory', verbose_name='商品归属库')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='日志创建时间')),
                ('type', models.CharField(choices=[('0', '建库'), ('1', '入库'), ('2', '出库'), ('3', '删库'), ('4', '改库')], max_length=10, verbose_name='日志类型')),
                ('dir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mycode.Directory', verbose_name='所建库')),
                ('good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mycode.Goods', verbose_name='操作商品')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='微信昵称')),
                ('openid', models.CharField(default='default', max_length=100, verbose_name='用户标识')),
                ('cookie', models.CharField(default='', max_length=100, verbose_name='用户认证标识')),
                ('gender', models.CharField(choices=[(1, '男'), (2, '女'), (0, '未知')], max_length=10, verbose_name='性别')),
                ('city', models.CharField(max_length=100, verbose_name='城市')),
                ('province', models.CharField(max_length=100, verbose_name='省份')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mycode.Profile', verbose_name='日志所属人'),
        ),
        migrations.AddField(
            model_name='directory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycode.Profile', verbose_name='拥有者'),
        ),
    ]
